// Autogenerated by Antigravity Universal Atomic Sub-Element Engine
export const ATOMS = {
  matrixCode: "[BTN-05 | INP-03 | CRD-02 | BDG-01 | ACC-03]",
  buttonPrimary: "rounded-full bg-transparent hover:bg-primary-500 border-2 border-primary-500 text-primary-600 dark:text-primary-300 hover:text-[color:var(--primary-contrast-text)] font-black uppercase tracking-wider px-8 py-3.5 transition-all min-h-[44px] inline-flex items-center justify-center gap-2",
  input: "rounded-none bg-transparent text-neutral-900 dark:text-neutral-100 border-b-2 border-neutral-400 dark:border-neutral-600 focus:border-primary-500 px-2 py-3 text-sm outline-none transition-all w-full font-semibold",
  card: "bg-white dark:bg-black text-neutral-900 dark:text-neutral-100 rounded-none border-2 border-neutral-900 dark:border-neutral-100 p-6 sm:p-8 shadow-[6px_6px_0px_#000] dark:shadow-[6px_6px_0px_#fff]",
  badge: "inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-black uppercase tracking-widest bg-primary-500 text-[color:var(--primary-contrast-text)] shadow-sm",
  accordion: "mb-3 rounded-none border-2 border-black dark:border-white p-5 bg-neutral-50 dark:bg-neutral-950 shadow-[3px_3px_0px_#000]",
};
