// ============================================================
// BRAND CONFIG — Kratos Moving
// Auto-generated by Antigravity White-Label Pro Max Engine
// ============================================================

export const BRAND = {
  // Company names
  name: "Kratos Moving",
  nameUpper: "KRATOS MOVING",
  legalName: "Kratos Group of Companies Inc.",
  shortName: "Kratos",

  // Logo & Branding
  logoSymbol: "K",
  logoUrl: "",
  faviconUrl: "",

  // Domain & URLs
  domain: "kratosmoving.com",
  websiteUrl: "https://www.kratosmoving.com",

  // Contact info
  phone: "(647) 255-8444",
  phoneRaw: "6472558444",
  phoneVanity: "Call Dispatch (647) 255-8444",
  email: "info@kratosmoving.com",
  hqAddress: "27 Roytec Rd, Unit 8B, Woodbridge, ON L4L 8E3",

  // Page metadata
  pageTitle: "Kratos Moving | Canada's #1 Trusted Moving Company",
  metaDescription:
    "Proudly serving all of Canada with Certified 5-Star moving and storage services. Call (647) 255-8444 for a free consultation.",

  // Slogans & taglines
  heroTagline: "CANADA'S #1 TRUSTED MOVING COMPANY",
  heroSubtitle: "Done As Promised — certified 5-star moving, packing & storage across Ontario & beyond.",
  rankingClaim: "Certified 5-Star Service — 3,000+ Google Reviews",

  // Referral program
  referralProgramName: "KRATOS REFERRAL REWARDS",
  referralGiveAmount: 50,
  referralGetAmount: 100,
  referralDefaultCode: "KRATOS50",
  referralTopEarning: '$1,000/month',

  // Booking
  bookingRefPrefix: "KRA",

  // Aria / accessibility (UI/UX Pro Max compliant)
  headerAriaLabel: "Kratos Moving Home",
} as const;
