// ============================================================
// BRAND CONFIG — Moving Company Mississauga | Advance Moving
// Auto-generated by Antigravity White-Label Pro Max Engine
// ============================================================

export const BRAND = {
  // Company names
  name: "Moving Company Mississauga | Advance Moving",
  nameUpper: "MOVING COMPANY MISSISSAUGA | ADVANCE MOVING",
  legalName: "Moving Company Mississauga | Advance Moving Inc.",
  shortName: "Moving",

  // Logo & Branding
  logoSymbol: "M",
  logoUrl: "/assets/brand/logo.png",
  faviconUrl: "/assets/brand/favicon.png",
  heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1920&q=80",

  // Domain & URLs
  domain: "advancemoving.ca",
  websiteUrl: "https://www.advancemoving.ca/",

  // Contact info
  phone: "(437) 989-7726",
  phoneRaw: "4379897726",
  phoneVanity: "Call Dispatch (437) 989-7726",
  email: "info@advancemoving.ca",
  hqAddress: "25 City View Dr, Etobicoke, ON M9W 5A7",

  // Page metadata
  pageTitle: "Moving Company Mississauga | Advance Moving",
  metaDescription:
    "Advance Moving is a trusted moving company in Mississauga offering residential, commercial, packing, storage, and short-distance moving services. Book now!",

  // Slogans & taglines
  heroTagline: "MOVING COMPANY IN MISSISSAUGA FAST, RELIABLE, AND FULLY INSURED",
  heroSubtitle: "Advance Moving is a trusted moving company in Mississauga offering residential, commercial, packing, storage, and short-distance moving services. Book now!",
  rankingClaim: "Trusted by thousands — Moving Company Mississauga | Advance Moving",

  // Referral program
  referralProgramName: "MOVING REFERRAL REWARDS",
  referralGiveAmount: 50,
  referralGetAmount: 100,
  referralDefaultCode: "MOVING50",
  referralTopEarning: '$1,000/month',

  // Booking
  bookingRefPrefix: "MOV",

  // Aria / accessibility (UI/UX Pro Max compliant)
  headerAriaLabel: "Moving Company Mississauga | Advance Moving Home",
} as const;
