// ============================================================
// BRAND CONFIG — Wellington and Co.
// Auto-generated by Antigravity White-Label Pro Max Engine
// ============================================================

export const BRAND = {
  // Company names
  name: "Wellington and Co.",
  nameUpper: "WELLINGTON AND CO.",
  legalName: "Wellington and Co. Inc.",
  shortName: "Wellington and Co.",

  // Logo & Branding
  logoSymbol: "W",
  logoUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=150&q=80",
  faviconUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=150&q=80",
  heroImage: "https://images.unsplash.com/photo-1555529733-0e670560f0e1?auto=format&fit=crop&w=1920&q=80",
  heroBgUrl: "",

  // Domain & URLs
  domain: "wellingtonandco.fake",
  websiteUrl: "https://wellingtonandco.fake/",

  // Contact info
  phone: "555-888-0021",
  phoneRaw: "5558880021",
  phoneVanity: "Call Dispatch 555-888-0021",
  email: "concierge@wellingtonandco.fake",
  hqAddress: "100 King St W, Suite 5600, Toronto, ON M5X 1C9",

  // Page metadata
  pageTitle: "Wellington and Co. | Premium Certified Movers",
  metaDescription:
    "Certified premium relocation services with guaranteed pricing and full insurance coverage.",

  // Slogans & taglines
  heroTagline: "CERTIFIED PREMIUM MOVING & STORAGE",
  heroSubtitle: "Done As Promised — certified 5-star moving, packing & storage across your region.",
  rankingClaim: "Certified 5-Star Service — 3,000+ Verified Reviews",

  // Referral program
  referralProgramName: "WELLINGTON AND CO. REFERRAL REWARDS",
  referralGiveAmount: 50,
  referralGetAmount: 100,
  referralDefaultCode: "WELLINGTON AND CO.50",
  referralTopEarning: '$1,000/month',

  // Booking
  bookingRefPrefix: "WEL",

  // Aria / accessibility (UI/UX Pro Max compliant)
  headerAriaLabel: "Wellington and Co. Home",
} as const;
