// ============================================================
// BRAND CONFIG — Throne Barbershop (Mock)
// Auto-generated by Antigravity White-Label Pro Max Engine
// ============================================================

export const BRAND = {
  // Company names
  name: "Throne Barbershop",
  nameUpper: "THRONE BARBERSHOP",
  legalName: "Throne Barbershop Inc.",
  shortName: "Throne",

  // Logo & Branding
  logoSymbol: "T",
  logoUrl: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=150&q=80",
  faviconUrl: "",
  heroImage: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?q=80&w=2074&auto=format&fit=crop",

  // Domain & URLs
  domain: "thronebarbershop.com",
  websiteUrl: "https://thronebarbershop.com/",

  // Contact info
  phone: "416-555-0199",
  phoneRaw: "4165550199",
  phoneVanity: "Call 416-555-0199",
  email: "info@thronebarbershop.com",
  hqAddress: "123 King St W, Toronto, ON",

  // Page metadata
  pageTitle: "Throne Barbershop | Premier Haircuts in Toronto",
  metaDescription: "Experience the art of a truly tailored men's haircut at Toronto's premier barbershop.",

  // Slogans & taglines
  heroTagline: "The Crown of Confidence",
  heroSubtitle: "Toronto's most award-winning barbershop. Expert cuts, classic service, and a modern vibe.",
  rankingClaim: "Rated #1 by Toronto Life",

  // Referral program
  referralProgramName: "THRONE REWARDS",
  referralGiveAmount: 15,
  referralGetAmount: 15,
  referralDefaultCode: "THRONE15",
  referralTopEarning: 'Free Cuts',

  // Booking
  bookingRefPrefix: "THR",

  // Aria / accessibility (UI/UX Pro Max compliant)
  headerAriaLabel: "Throne Barbershop Home",
} as const;
