const fs = require('fs');
const path = require('path');

// Usage: node scripts/populate_template.cjs <path_to_profile.json>
const profilePath = process.argv[2];

if (!profilePath || !fs.existsSync(profilePath)) {
  console.error('❌ Error: Please provide a valid path to a target asset profile JSON file.');
  console.log('Usage: node scripts/populate_template.cjs path/to/target-profile.json');
  process.exit(1);
}

console.log(`📥 Loading target website asset profile from: ${profilePath}...`);
const profile = JSON.parse(fs.readFileSync(profilePath, 'utf8'));

// Helper to safely format string literals for TypeScript code generation
const s = (val, defaultVal) => JSON.stringify(val !== undefined && val !== null ? val : defaultVal);

// 1. Update src/config/brand.ts
const brandConfigPath = path.join(__dirname, '..', 'src', 'config', 'brand.ts');
const brandContent = `// ============================================================
// BRAND CONFIG — ${profile.name || 'White-Label Relocation'}
// Auto-generated by Antigravity White-Label Pro Max Engine
// ============================================================

export const BRAND = {
  // Company names
  name: ${s(profile.name, 'Custom Relocations')},
  nameUpper: ${s((profile.name || 'Custom Relocations').toUpperCase(), 'CUSTOM RELOCATIONS')},
  legalName: ${s(profile.legalName, (profile.name || 'Custom Relocations') + ' Inc.')},
  shortName: ${s(profile.shortName, profile.name?.split(' ')[0] || 'Relocations')},

  // Logo
  logoSymbol: ${s(profile.logoSymbol, profile.name ? profile.name[0] : 'C')},

  // Domain & URLs
  domain: ${s(profile.domain, 'customrelocations.com')},
  websiteUrl: ${s(profile.websiteUrl, 'https://www.customrelocations.com')},

  // Contact info
  phone: ${s(profile.phone, '(800) 555-0199')},
  phoneRaw: ${s((profile.phone || '8005550199').replace(/[^0-9]/g, ''), '8005550199')},
  phoneVanity: ${s('Call Dispatch ' + (profile.phone || '(800) 555-0199'), 'Call Dispatch (800) 555-0199')},
  email: ${s(profile.email, 'info@customrelocations.com')},
  hqAddress: ${s(profile.hqAddress, '100 King St W, Suite 5600, Toronto, ON M5X 1C9')},

  // Page metadata
  pageTitle: ${s(profile.pageTitle, (profile.name || 'Custom Relocations') + ' | Premium Certified Movers')},
  metaDescription:
    ${s(profile.metaDescription, 'Certified premium relocation services with guaranteed pricing and full insurance coverage.')},

  // Slogans & taglines
  heroTagline: ${s((profile.heroTagline || 'CERTIFIED PREMIUM MOVING & STORAGE').toUpperCase(), 'CERTIFIED PREMIUM MOVING & STORAGE')},
  heroSubtitle: ${s(profile.heroSubtitle, 'Done As Promised — certified 5-star moving, packing & storage across your region.')},
  rankingClaim: ${s(profile.rankingClaim, 'Certified 5-Star Service — 3,000+ Verified Reviews')},

  // Referral program
  referralProgramName: ${s((profile.shortName || profile.name?.split(' ')[0] || 'VIP').toUpperCase() + ' REFERRAL REWARDS', 'VIP REFERRAL REWARDS')},
  referralGiveAmount: ${Number(profile.referralGiveAmount || 50)},
  referralGetAmount: ${Number(profile.referralGetAmount || 100)},
  referralDefaultCode: ${s((profile.shortName || profile.name?.split(' ')[0] || 'VIP').toUpperCase() + '50', 'VIP50')},
  referralTopEarning: '$1,000/month',

  // Booking
  bookingRefPrefix: ${s((profile.shortName ? profile.shortName.substring(0, 3) : 'VIP').toUpperCase(), 'VIP')},

  // Aria / accessibility (UI/UX Pro Max compliant)
  headerAriaLabel: ${s((profile.name || 'Custom Relocations') + ' Home', 'Custom Relocations Home')},
} as const;
`;

fs.writeFileSync(brandConfigPath, brandContent, 'utf8');
console.log('✅ Updated src/config/brand.ts');

// 2. Update src/config/theme.ts if custom color theme provided
if (profile.theme && (profile.theme.primary || profile.theme.secondary)) {
  const themeConfigPath = path.join(__dirname, '..', 'src', 'config', 'theme.ts');
  const themeContent = `// ============================================================
// THEME CONFIG — ${profile.name || 'Custom Relocations'}
// UI/UX Pro Max Aesthetic: ${profile.theme.primary || 'amber'} (Major) + ${profile.theme.secondary || 'black'} (Minor)
// ============================================================

export const THEME = {
  colors: {
    primary: ${s(profile.theme.primary, 'amber')},
    secondary: ${s(profile.theme.secondary, 'black')},
  },
  backgrounds: {
    page: ${s(profile.theme.bgPage, '#ffffff')},
    section: ${s(profile.theme.bgSection, '#fffbeb')},
    card: '#ffffff',
    cardAlt: ${s(profile.theme.bgCardAlt, '#fef3c7')},
    sectionAlt: ${s(profile.theme.bgSectionAlt, '#f8fafc')},
    heroOverlay: ${s(profile.theme.bgHeroOverlay, '#fffcf5')},
    footerBottom: ${s(profile.theme.bgFooter, '#09090b')},
  },
  focus: {
    ringColor: ${s(profile.theme.focusRing, '#d97706')},
    selectionBg: ${s(profile.theme.selectionBg, '#fbbf24')},
    selectionText: '#000000',
  },
  fonts: {
    heading: 'Montserrat',
    body: 'Inter',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Montserrat:wght@400;500;600;700;800&display=swap',
  },
} as const;
`;
  fs.writeFileSync(themeConfigPath, themeContent, 'utf8');
  console.log('✅ Updated src/config/theme.ts with targeted Major/Minor color aesthetics');
}

// 3. Update mock data references if applicable
const mockDataPath = path.join(__dirname, '..', 'src', 'data', 'mockData.ts');
if (fs.existsSync(mockDataPath) && profile.oldBrandNameToReplace) {
  let mockContent = fs.readFileSync(mockDataPath, 'utf8');
  const oldRegex = new RegExp(profile.oldBrandNameToReplace, 'gi');
  mockContent = mockContent.replace(oldRegex, profile.name);
  fs.writeFileSync(mockDataPath, mockContent, 'utf8');
  console.log('✅ Updated brand references in src/data/mockData.ts');
}

console.log('🚀 Modular substitution complete! The codebase is ready for `npm run build` and Vercel edge deployment.');
